import{a as g,S as b,i as y}from"./assets/vendor-f736e62a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";async function f(s,e,o){const i=new URLSearchParams({key:"43777991-fc34414997ff3024de4420c7b",image_type:"photo",q:s,orientation:"horizontal",safesearch:"true",page:e,per_page:o});return(await g(`?${i}`)).data}const L=document.querySelector(".list");let w=new b(".gallery-item a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"});function h(s){const e=s.hits.map(o=>`<li class="gallery-item" >
    <a href= ${o.largeImageURL}>
	<img
			class = "gallery-image"  
			src = "${o.webformatURL}"  
			alt = "${o.tags}"
    />
	</a>
    <ul class = "gallery-alt">
        <li class="gallery-alt-photo">Likes <p class = 'like'>${o.likes}</p></li>
        <li class="gallery-alt-photo">Views <p class = 'like'>${o.views}</p></li>
        <li class="gallery-alt-photo">Comments <p class = 'like'>${o.comments}</p></li>
        <li class="gallery-alt-photo">Downloads <p class = 'like'>${o.downloads}</p></li>
    </ul>
</li>`).join("");L.insertAdjacentHTML("beforeend",e),w.refresh()}const v=()=>{y.error({message:"Sorry, there are no images matching your search query. Please try again!",icon:"",backgroundColor:"#EF4040",position:"topRight",progressBarColor:"#B51B1B",messageColor:"white",close:!1,timeout:2e3})},B=()=>{y.error({message:"We're sorry, but you've reached the end of search results.",icon:"",backgroundColor:"#EF4040",position:"topRight",progressBarColor:"#B51B1B",messageColor:"white",close:!1,timeout:2e3})},S=()=>{y.error({message:"Fill in the search field.Please try again!",icon:"",backgroundColor:"#EF4040",position:"topRight",progressBarColor:"#B51B1B",messageColor:"white",close:!1,timeout:2e3})},d=document.querySelector(".input"),E=document.querySelector(".form"),C=document.querySelector(".list"),l=document.querySelector(".btn-more"),n=document.querySelector(".loader");n.style.display="none";d.addEventListener("input",s=>{s.target.style.border="1px solid #4E75FF"});d.addEventListener("blur",s=>{s.target.style.border="1px solid #808080"});let a=1,u=15,c="",m=0;E.addEventListener("submit",async s=>{if(s.preventDefault(),C.innerHTML="",n.style.display="block",l.style.display="none",a=1,c=d.value.trim(),c===""){S(),n.style.display="none";return}try{const e=await f(c,a,u);if(e.totalHits===0){v(),l.style.display="none";return}else h(e),d.value="",l.style.display="block",e.totalHits<u&&(B(),l.style.display="none");console.log("🚀 ~ form.addEventListener ~ photo:",e)}catch(e){console.error(e)}finally{n.style.display="none"}});const q=()=>{const o=document.querySelector(".list").getBoundingClientRect().height*2;window.scrollBy({top:o,left:0,behavior:"smooth"})};l.addEventListener("click",async s=>{a+=1;try{const e=await f(c,a,u);h(e),q(),m=Math.ceil(e.totalHits/u),a===m&&(l.style.display="none")}catch(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
