import{a as p,S as h,i as y}from"./assets/vendor-f736e62a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();p.defaults.baseURL="https://pixabay.com/api/";let m=3,d=1,u=0;async function g(o,e){const t=new URLSearchParams({key:"43777991-fc34414997ff3024de4420c7b",image_type:"photo",q:o,orientation:"horizontal",safesearch:"true",page:e,per_page:m});return(await p(`?${t}`)).data}async function b(o,e){e=1,console.log("🚀 ~ onSearchMore ~ page:",e);const t=await g(o,e);e=1;try{const{totalHits:l,hits:r}=t;return u=Math.ceil(l/m),{hits:r,totalPages:u}}catch(l){console.error(l)}}const L=document.querySelector(".list");let v=new h(".gallery-item a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"});function f(o){const e=o.hits.map(t=>`<li class="gallery-item" >
    <a href= ${t.largeImageURL}>
	<img
			class = "gallery-image"  
			src = "${t.webformatURL}"  
			alt = "${t.tags}"
    />
	</a>
    <ul class = "gallery-alt">
        <li class="gallery-alt-photo">Likes <p class = 'like'>${t.likes}</p></li>
        <li class="gallery-alt-photo">Views <p class = 'like'>${t.views}</p></li>
        <li class="gallery-alt-photo">Comments <p class = 'like'>${t.comments}</p></li>
        <li class="gallery-alt-photo">Downloads <p class = 'like'>${t.downloads}</p></li>
    </ul>
</li>`).join("");L.insertAdjacentHTML("beforeend",e),v.refresh()}const E=()=>{y.error({message:"Sorry, there are no images matching your search query. Please try again!",icon:"",backgroundColor:"#EF4040",position:"topRight",progressBarColor:"#B51B1B",messageColor:"white",close:!1,timeout:2e3})},S=document.querySelector(".form"),w=document.querySelector(".list"),i=document.querySelector(".btn-more"),n=document.querySelector(".loader");n.style.display="none";const a=document.querySelector(".input");a.addEventListener("input",o=>{o.target.style.border="1px solid #4E75FF"});a.addEventListener("blur",o=>{o.target.style.border="1px solid #808080"});a.addEventListener("input",o=>{a.value=o.target.value});S.addEventListener("submit",async o=>{w.innerHTML="",n.style.display="block",o.preventDefault();const e=await g(a.value,d);console.log("🚀 ~ form.addEventListener ~ photo:",e);try{a.value.trim()===""||e.totalHits===0?(E(),n.style.display="none",i.style.display="none"):(f(e),i.style.display="block",n.style.display="none")}catch(t){console.error(t)}});i.addEventListener("click",async o=>{o.preventDefault();const e=await b(a.value,d);console.log("🚀 ~ btnMore.addEventListener ~ page_first:",d),console.log("🚀 ~ btnMore.addEventListener ~ photoMore:",e);try{f(e),e.hits.length>=e.totalPages&&(y.error({message:"We're sorry, but you've reached the end of search results.",icon:"",backgroundColor:"#EF4040"}),i.style.display="none")}catch(t){console.log(t)}});
//# sourceMappingURL=commonHelpers.js.map
